version: "3.8"
services:
  bot:
    build: .
    command: python3 main.py
    environment:
      - DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
      - PERSISTENCE_CIPHER_TOKEN=$PERSISTENCE_CIPHER_TOKEN
    volumes:
      - type: bind
        source: ./surveys.db
        target: /cfc-survey-bot/surveys.db
