version: "3.8"
services:
  bot:
    build: .
    command: python3 main.py
    environment:
      - DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN
      - PERSISTENCE_CIPHER_TOKEN=$PERSISTENCE_CIPHER_TOKEN
    volumes:
      - ${PWD}/surveys.db:/cfc-survey-bot/surveys.db
      - ${PWD}/surveys.db-wal:/cfc-survey-bot/surveys.db-wal
      - ${PWD}/surveys.db-shm:/cfc-survey-bot/surveys.db-shm
    restart: always
